[package]
name = "xtask"
edition = "2021"
publish = false
version = "0.1.0"

[dependencies]
# This dependency should stay in line with your router version

apollo-router-scaffold = { git = "ssh://git@github.com/TheHackerApp/apollo-router.git", branch = "main" }
anyhow.workspace = true
clap = "4.4"
